# Generated by Django 4.0.3 on 2022-05-11 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('cod_dane', models.IntegerField(default=None, primary_key=True, serialize=False, verbose_name='Codigo_dane')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Departaments',
            fields=[
                ('departament', models.CharField(max_length=80, verbose_name='Departamento')),
                ('cod_dane', models.IntegerField(default=None, primary_key=True, serialize=False, verbose_name='Codigo_dane')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Workeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lastName', models.CharField(max_length=100, verbose_name='Apellido')),
                ('mail', models.CharField(max_length=200, verbose_name='Correo')),
                ('bornDate', models.DateField(blank=True, verbose_name='Fecha de nacimiento')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('photo', models.ImageField(blank=True, default='null', null=True, upload_to='clientes')),
                ('mobile', models.IntegerField(blank=True, default=None, null=True, verbose_name='Celular')),
                ('descripcion_personal', models.TextField(blank=True, default=None, null=True, verbose_name='Descripcion')),
                ('ciudad', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.cities', verbose_name='Ciudad')),
                ('gender', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.genders')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
            },
        ),
        migrations.CreateModel(
            name='Neighborhoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(max_length=80, verbose_name='Barrio')),
                ('cityId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.cities', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lastName', models.CharField(max_length=100, verbose_name='Apellido')),
                ('mail', models.CharField(max_length=200, verbose_name='Correo')),
                ('bornDate', models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de nacimiento')),
                ('password', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Password')),
                ('photo', models.ImageField(blank=True, default='null', null=True, upload_to='clientes')),
                ('mobile', models.IntegerField(blank=True, default=None, null=True, verbose_name='Celular')),
                ('ciudad', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.cities', verbose_name='Ciudad')),
                ('gender', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.genders')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.AddField(
            model_name='cities',
            name='departametId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.departaments', verbose_name='Departamento'),
        ),
    ]
