# Generated by Django 4.0.3 on 2022-05-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workeds',
            name='bornDate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
