# Generated by Django 4.0.4 on 2022-05-22 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default=None, null=True, verbose_name='Descripcion')),
                ('evidenciaPhoto', models.ImageField(upload_to='evidencias/%m/%d/')),
                ('trabajador', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Evidencia trabajador',
                'verbose_name_plural': 'Evidencias trabajadores',
            },
        ),
    ]
